// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PermissionDoorClient is the client API for PermissionDoor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionDoorClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	//
	//Set policies to Role.
	SetRolePolicies(ctx context.Context, in *SetRolePoliciesRequest, opts ...grpc.CallOption) (*SetRolePoliciesResponse, error)
	//
	//Authenticate Role permission.
	AuthenticateRolePolicy(ctx context.Context, in *AuthenticateRolePolicyRequest, opts ...grpc.CallOption) (*AuthenticateRolePolicyResponse, error)
	AuthenticateRolesPolicy(ctx context.Context, in *AuthenticateRolesPolicyRequest, opts ...grpc.CallOption) (*AuthenticateRolesPolicyResponse, error)
	//
	//Get all policies of role.
	GetRolePolicies(ctx context.Context, in *GetRolePoliciesRequest, opts ...grpc.CallOption) (*GetRolePoliciesResponse, error)
	//
	//Cancel some policies of role.
	UnsetRolePolicies(ctx context.Context, in *UnsetRolePoliciesRequest, opts ...grpc.CallOption) (*UnsetRolePoliciesResponse, error)
	//
	//Delete data of role.
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
	//
	//Delete resources.
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	AuthenticateUserPolicyByID(ctx context.Context, in *AuthenticateUserPolicyByIDRequest, opts ...grpc.CallOption) (*AuthenticateUserPolicyByIDResponse, error)
}

type permissionDoorClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionDoorClient(cc grpc.ClientConnInterface) PermissionDoorClient {
	return &permissionDoorClient{cc}
}

func (c *permissionDoorClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) SetRolePolicies(ctx context.Context, in *SetRolePoliciesRequest, opts ...grpc.CallOption) (*SetRolePoliciesResponse, error) {
	out := new(SetRolePoliciesResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/SetRolePolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) AuthenticateRolePolicy(ctx context.Context, in *AuthenticateRolePolicyRequest, opts ...grpc.CallOption) (*AuthenticateRolePolicyResponse, error) {
	out := new(AuthenticateRolePolicyResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/AuthenticateRolePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) AuthenticateRolesPolicy(ctx context.Context, in *AuthenticateRolesPolicyRequest, opts ...grpc.CallOption) (*AuthenticateRolesPolicyResponse, error) {
	out := new(AuthenticateRolesPolicyResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/AuthenticateRolesPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) GetRolePolicies(ctx context.Context, in *GetRolePoliciesRequest, opts ...grpc.CallOption) (*GetRolePoliciesResponse, error) {
	out := new(GetRolePoliciesResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/GetRolePolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) UnsetRolePolicies(ctx context.Context, in *UnsetRolePoliciesRequest, opts ...grpc.CallOption) (*UnsetRolePoliciesResponse, error) {
	out := new(UnsetRolePoliciesResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/UnsetRolePolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	out := new(DeleteRoleResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/DeleteResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionDoorClient) AuthenticateUserPolicyByID(ctx context.Context, in *AuthenticateUserPolicyByIDRequest, opts ...grpc.CallOption) (*AuthenticateUserPolicyByIDResponse, error) {
	out := new(AuthenticateUserPolicyByIDResponse)
	err := c.cc.Invoke(ctx, "/permission.door.v1.PermissionDoor/AuthenticateUserPolicyByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionDoorServer is the server API for PermissionDoor service.
// All implementations must embed UnimplementedPermissionDoorServer
// for forward compatibility
type PermissionDoorServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	//
	//Set policies to Role.
	SetRolePolicies(context.Context, *SetRolePoliciesRequest) (*SetRolePoliciesResponse, error)
	//
	//Authenticate Role permission.
	AuthenticateRolePolicy(context.Context, *AuthenticateRolePolicyRequest) (*AuthenticateRolePolicyResponse, error)
	AuthenticateRolesPolicy(context.Context, *AuthenticateRolesPolicyRequest) (*AuthenticateRolesPolicyResponse, error)
	//
	//Get all policies of role.
	GetRolePolicies(context.Context, *GetRolePoliciesRequest) (*GetRolePoliciesResponse, error)
	//
	//Cancel some policies of role.
	UnsetRolePolicies(context.Context, *UnsetRolePoliciesRequest) (*UnsetRolePoliciesResponse, error)
	//
	//Delete data of role.
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error)
	//
	//Delete resources.
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	AuthenticateUserPolicyByID(context.Context, *AuthenticateUserPolicyByIDRequest) (*AuthenticateUserPolicyByIDResponse, error)
	mustEmbedUnimplementedPermissionDoorServer()
}

// UnimplementedPermissionDoorServer must be embedded to have forward compatible implementations.
type UnimplementedPermissionDoorServer struct {
}

func (UnimplementedPermissionDoorServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedPermissionDoorServer) SetRolePolicies(context.Context, *SetRolePoliciesRequest) (*SetRolePoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRolePolicies not implemented")
}
func (UnimplementedPermissionDoorServer) AuthenticateRolePolicy(context.Context, *AuthenticateRolePolicyRequest) (*AuthenticateRolePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateRolePolicy not implemented")
}
func (UnimplementedPermissionDoorServer) AuthenticateRolesPolicy(context.Context, *AuthenticateRolesPolicyRequest) (*AuthenticateRolesPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateRolesPolicy not implemented")
}
func (UnimplementedPermissionDoorServer) GetRolePolicies(context.Context, *GetRolePoliciesRequest) (*GetRolePoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolePolicies not implemented")
}
func (UnimplementedPermissionDoorServer) UnsetRolePolicies(context.Context, *UnsetRolePoliciesRequest) (*UnsetRolePoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsetRolePolicies not implemented")
}
func (UnimplementedPermissionDoorServer) DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedPermissionDoorServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedPermissionDoorServer) AuthenticateUserPolicyByID(context.Context, *AuthenticateUserPolicyByIDRequest) (*AuthenticateUserPolicyByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUserPolicyByID not implemented")
}
func (UnimplementedPermissionDoorServer) mustEmbedUnimplementedPermissionDoorServer() {}

// UnsafePermissionDoorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionDoorServer will
// result in compilation errors.
type UnsafePermissionDoorServer interface {
	mustEmbedUnimplementedPermissionDoorServer()
}

func RegisterPermissionDoorServer(s grpc.ServiceRegistrar, srv PermissionDoorServer) {
	s.RegisterService(&PermissionDoor_ServiceDesc, srv)
}

func _PermissionDoor_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_SetRolePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRolePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).SetRolePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/SetRolePolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).SetRolePolicies(ctx, req.(*SetRolePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_AuthenticateRolePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRolePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).AuthenticateRolePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/AuthenticateRolePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).AuthenticateRolePolicy(ctx, req.(*AuthenticateRolePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_AuthenticateRolesPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRolesPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).AuthenticateRolesPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/AuthenticateRolesPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).AuthenticateRolesPolicy(ctx, req.(*AuthenticateRolesPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_GetRolePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).GetRolePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/GetRolePolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).GetRolePolicies(ctx, req.(*GetRolePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_UnsetRolePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsetRolePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).UnsetRolePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/UnsetRolePolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).UnsetRolePolicies(ctx, req.(*UnsetRolePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionDoor_AuthenticateUserPolicyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserPolicyByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionDoorServer).AuthenticateUserPolicyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.door.v1.PermissionDoor/AuthenticateUserPolicyByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionDoorServer).AuthenticateUserPolicyByID(ctx, req.(*AuthenticateUserPolicyByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionDoor_ServiceDesc is the grpc.ServiceDesc for PermissionDoor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionDoor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.door.v1.PermissionDoor",
	HandlerType: (*PermissionDoorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _PermissionDoor_Version_Handler,
		},
		{
			MethodName: "SetRolePolicies",
			Handler:    _PermissionDoor_SetRolePolicies_Handler,
		},
		{
			MethodName: "AuthenticateRolePolicy",
			Handler:    _PermissionDoor_AuthenticateRolePolicy_Handler,
		},
		{
			MethodName: "AuthenticateRolesPolicy",
			Handler:    _PermissionDoor_AuthenticateRolesPolicy_Handler,
		},
		{
			MethodName: "GetRolePolicies",
			Handler:    _PermissionDoor_GetRolePolicies_Handler,
		},
		{
			MethodName: "UnsetRolePolicies",
			Handler:    _PermissionDoor_UnsetRolePolicies_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _PermissionDoor_DeleteRole_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _PermissionDoor_DeleteResource_Handler,
		},
		{
			MethodName: "AuthenticateUserPolicyByID",
			Handler:    _PermissionDoor_AuthenticateUserPolicyByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/permission-door.proto",
}
